# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/processor/processor.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor || ORIG_REF_NAME==processor} -quiet] -quiet

# IP: bd/processor/ip/processor_Control_Unit_0_0/processor_Control_Unit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_Control_Unit_0_0 || ORIG_REF_NAME==processor_Control_Unit_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_S_Controller_0_0/processor_S_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_S_Controller_0_0 || ORIG_REF_NAME==processor_S_Controller_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_F_controller_0_0/processor_F_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_F_controller_0_0 || ORIG_REF_NAME==processor_F_controller_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_R_Controller_0_0/processor_R_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_R_Controller_0_0 || ORIG_REF_NAME==processor_R_Controller_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_ri_controller_0_0/processor_ri_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_ri_controller_0_0 || ORIG_REF_NAME==processor_ri_controller_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_ALU_Controller_0_0/processor_ALU_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_ALU_Controller_0_0 || ORIG_REF_NAME==processor_ALU_Controller_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_MDR_Controller_0_0/processor_MDR_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_MDR_Controller_0_0 || ORIG_REF_NAME==processor_MDR_Controller_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_mar_controller_0_0/processor_mar_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_mar_controller_0_0 || ORIG_REF_NAME==processor_mar_controller_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_pc_controller_0_0/processor_pc_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_pc_controller_0_0 || ORIG_REF_NAME==processor_pc_controller_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_FGI_Controller_0_0/processor_FGI_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_FGI_Controller_0_0 || ORIG_REF_NAME==processor_FGI_Controller_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_FGO_Controller_0_0/processor_FGO_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_FGO_Controller_0_0 || ORIG_REF_NAME==processor_FGO_Controller_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_WR_Controller_0_0/processor_WR_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_WR_Controller_0_0 || ORIG_REF_NAME==processor_WR_Controller_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_RAM_4Kx16_0_0/processor_RAM_4Kx16_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_RAM_4Kx16_0_0 || ORIG_REF_NAME==processor_RAM_4Kx16_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_outr_controller_0_0/processor_outr_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_outr_controller_0_0 || ORIG_REF_NAME==processor_outr_controller_0_0} -quiet] -quiet

# IP: bd/processor/ip/processor_clk_wiz_0/processor_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_clk_wiz_0 || ORIG_REF_NAME==processor_clk_wiz_0} -quiet] -quiet

# IP: bd/processor/ip/processor_E_controller_0_0/processor_E_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==processor_E_controller_0_0 || ORIG_REF_NAME==processor_E_controller_0_0} -quiet] -quiet

# XDC: c:/Users/HP/Desktop/up/processor/processor.gen/sources_1/bd/processor/processor_ooc.xdc
