# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Full_PB/Full_PB.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB || ORIG_REF_NAME==Full_PB} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_mar_controller_0_0/Full_PB_mar_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_mar_controller_0_0 || ORIG_REF_NAME==Full_PB_mar_controller_0_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_Control_Unit_0_0/Full_PB_Control_Unit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_Control_Unit_0_0 || ORIG_REF_NAME==Full_PB_Control_Unit_0_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_MDR_Controller_0_0/Full_PB_MDR_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_MDR_Controller_0_0 || ORIG_REF_NAME==Full_PB_MDR_Controller_0_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_F_controller_0_0/Full_PB_F_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_F_controller_0_0 || ORIG_REF_NAME==Full_PB_F_controller_0_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_S_Controller_0_0/Full_PB_S_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_S_Controller_0_0 || ORIG_REF_NAME==Full_PB_S_Controller_0_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_WR_Controller_0_0/Full_PB_WR_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_WR_Controller_0_0 || ORIG_REF_NAME==Full_PB_WR_Controller_0_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_ALU_Controller_0_0/Full_PB_ALU_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_ALU_Controller_0_0 || ORIG_REF_NAME==Full_PB_ALU_Controller_0_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_outr_controller_0_0/Full_PB_outr_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_outr_controller_0_0 || ORIG_REF_NAME==Full_PB_outr_controller_0_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_ri_controller_0_0/Full_PB_ri_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_ri_controller_0_0 || ORIG_REF_NAME==Full_PB_ri_controller_0_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_pc_controller_0_0/Full_PB_pc_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_pc_controller_0_0 || ORIG_REF_NAME==Full_PB_pc_controller_0_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_FGI_Controller_0_0/Full_PB_FGI_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_FGI_Controller_0_0 || ORIG_REF_NAME==Full_PB_FGI_Controller_0_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_FGO_Controller_0_0/Full_PB_FGO_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_FGO_Controller_0_0 || ORIG_REF_NAME==Full_PB_FGO_Controller_0_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_E_controller_0_0/Full_PB_E_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_E_controller_0_0 || ORIG_REF_NAME==Full_PB_E_controller_0_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_clk_wiz_0/Full_PB_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_clk_wiz_0 || ORIG_REF_NAME==Full_PB_clk_wiz_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_clk_wiz_1_0/Full_PB_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_clk_wiz_1_0 || ORIG_REF_NAME==Full_PB_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_clk_wiz_2_0/Full_PB_clk_wiz_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_clk_wiz_2_0 || ORIG_REF_NAME==Full_PB_clk_wiz_2_0} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_R_Controller_0_1/Full_PB_R_Controller_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_R_Controller_0_1 || ORIG_REF_NAME==Full_PB_R_Controller_0_1} -quiet] -quiet

# IP: bd/Full_PB/ip/Full_PB_RAM_4Kx16_0_1/Full_PB_RAM_4Kx16_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Full_PB_RAM_4Kx16_0_1 || ORIG_REF_NAME==Full_PB_RAM_4Kx16_0_1} -quiet] -quiet

# XDC: c:/Users/HP/Desktop/up/Full_PBase/Full_PBase.gen/sources_1/bd/Full_PB/Full_PB_ooc.xdc
