# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/HP/Desktop/up/Full_PBase/Full_PBase.srcs/sources_1/bd/Full_PB/ip/Full_PB_clk_wiz_0/Full_PB_clk_wiz_0.xci
# IP: The module: 'Full_PB_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/HP/Desktop/up/Full_PBase/Full_PBase.gen/sources_1/bd/Full_PB/ip/Full_PB_clk_wiz_0/Full_PB_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Full_PB_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/HP/Desktop/up/Full_PBase/Full_PBase.gen/sources_1/bd/Full_PB/ip/Full_PB_clk_wiz_0/Full_PB_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Full_PB_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/HP/Desktop/up/Full_PBase/Full_PBase.gen/sources_1/bd/Full_PB/ip/Full_PB_clk_wiz_0/Full_PB_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Full_PB_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/HP/Desktop/up/Full_PBase/Full_PBase.srcs/sources_1/bd/Full_PB/ip/Full_PB_clk_wiz_0/Full_PB_clk_wiz_0.xci
# IP: The module: 'Full_PB_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/HP/Desktop/up/Full_PBase/Full_PBase.gen/sources_1/bd/Full_PB/ip/Full_PB_clk_wiz_0/Full_PB_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Full_PB_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/HP/Desktop/up/Full_PBase/Full_PBase.gen/sources_1/bd/Full_PB/ip/Full_PB_clk_wiz_0/Full_PB_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Full_PB_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/HP/Desktop/up/Full_PBase/Full_PBase.gen/sources_1/bd/Full_PB/ip/Full_PB_clk_wiz_0/Full_PB_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Full_PB_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
